/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <android/log.h>
#include <stddef.h>
#include "log.h"
/* Header for class net_yrom_screenrecorder_rtmp_RtmpClient */

#ifndef _Included_net_yrom_screenrecorder_rtmp_RtmpClient
#define _Included_net_yrom_screenrecorder_rtmp_RtmpClient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_yrom_screenrecorder_rtmp_RtmpClient
 * Method:    open
 * Signature: (Ljava/lang/String;Z)J
 */
JNIEXPORT jlong JNICALL Java_net_yrom_screenrecorder_rtmp_RtmpClient_open
  (JNIEnv *, jclass, jstring, jboolean);

/*
 * Class:     net_yrom_screenrecorder_rtmp_RtmpClient
 * Method:    read
 * Signature: (J[BII)I
 */
JNIEXPORT jint JNICALL Java_net_yrom_screenrecorder_rtmp_RtmpClient_read
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jint);

/*
 * Class:     net_yrom_screenrecorder_rtmp_RtmpClient
 * Method:    write
 * Signature: (J[BIII)I
 */
JNIEXPORT jint JNICALL Java_net_yrom_screenrecorder_rtmp_RtmpClient_write
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jint, jint);

/*
 * Class:     net_yrom_screenrecorder_rtmp_RtmpClient
 * Method:    close
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_net_yrom_screenrecorder_rtmp_RtmpClient_close
 (JNIEnv * env,jlong , jobject );

/*
 * Class:     net_yrom_screenrecorder_rtmp_RtmpClient
 * Method:    getIpAddr
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_yrom_screenrecorder_rtmp_RtmpClient_getIpAddr
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
